#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BookASMWAD")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertadministrator(administrator instance);
  partial void Updateadministrator(administrator instance);
  partial void Deleteadministrator(administrator instance);
  partial void Insertauthor(author instance);
  partial void Updateauthor(author instance);
  partial void Deleteauthor(author instance);
  partial void Insertbook_new(book_new instance);
  partial void Updatebook_new(book_new instance);
  partial void Deletebook_new(book_new instance);
  partial void Insertcart(cart instance);
  partial void Updatecart(cart instance);
  partial void Deletecart(cart instance);
  partial void Insertcategory(category instance);
  partial void Updatecategory(category instance);
  partial void Deletecategory(category instance);
  partial void Insertcategory_product(category_product instance);
  partial void Updatecategory_product(category_product instance);
  partial void Deletecategory_product(category_product instance);
  partial void Insertcustomer(customer instance);
  partial void Updatecustomer(customer instance);
  partial void Deletecustomer(customer instance);
  partial void Insertcustomer_address(customer_address instance);
  partial void Updatecustomer_address(customer_address instance);
  partial void Deletecustomer_address(customer_address instance);
  partial void Insertorder_product(order_product instance);
  partial void Updateorder_product(order_product instance);
  partial void Deleteorder_product(order_product instance);
  partial void Insertpaymen(paymen instance);
  partial void Updatepaymen(paymen instance);
  partial void Deletepaymen(paymen instance);
  partial void Insertproducer(producer instance);
  partial void Updateproducer(producer instance);
  partial void Deleteproducer(producer instance);
  partial void Insertproduct(product instance);
  partial void Updateproduct(product instance);
  partial void Deleteproduct(product instance);
  partial void Insertproduct_type(product_type instance);
  partial void Updateproduct_type(product_type instance);
  partial void Deleteproduct_type(product_type instance);
  partial void Insertref_product_order(ref_product_order instance);
  partial void Updateref_product_order(ref_product_order instance);
  partial void Deleteref_product_order(ref_product_order instance);
  partial void Insertreview(review instance);
  partial void Updatereview(review instance);
  partial void Deletereview(review instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BookASMWADConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<administrator> administrators
	{
		get
		{
			return this.GetTable<administrator>();
		}
	}
	
	public System.Data.Linq.Table<author> authors
	{
		get
		{
			return this.GetTable<author>();
		}
	}
	
	public System.Data.Linq.Table<book_new> book_news
	{
		get
		{
			return this.GetTable<book_new>();
		}
	}
	
	public System.Data.Linq.Table<cart> carts
	{
		get
		{
			return this.GetTable<cart>();
		}
	}
	
	public System.Data.Linq.Table<category> categories
	{
		get
		{
			return this.GetTable<category>();
		}
	}
	
	public System.Data.Linq.Table<category_product> category_products
	{
		get
		{
			return this.GetTable<category_product>();
		}
	}
	
	public System.Data.Linq.Table<customer> customers
	{
		get
		{
			return this.GetTable<customer>();
		}
	}
	
	public System.Data.Linq.Table<customer_address> customer_addresses
	{
		get
		{
			return this.GetTable<customer_address>();
		}
	}
	
	public System.Data.Linq.Table<order_product> order_products
	{
		get
		{
			return this.GetTable<order_product>();
		}
	}
	
	public System.Data.Linq.Table<paymen> paymens
	{
		get
		{
			return this.GetTable<paymen>();
		}
	}
	
	public System.Data.Linq.Table<producer> producers
	{
		get
		{
			return this.GetTable<producer>();
		}
	}
	
	public System.Data.Linq.Table<product> products
	{
		get
		{
			return this.GetTable<product>();
		}
	}
	
	public System.Data.Linq.Table<product_type> product_types
	{
		get
		{
			return this.GetTable<product_type>();
		}
	}
	
	public System.Data.Linq.Table<ref_product_order> ref_product_orders
	{
		get
		{
			return this.GetTable<ref_product_order>();
		}
	}
	
	public System.Data.Linq.Table<review> reviews
	{
		get
		{
			return this.GetTable<review>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.administrator")]
public partial class administrator : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string @__email;
	
	private string @__user;
	
	private string @__password;
	
	private int @__position;
	
	private EntitySet<review> _reviews;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_emailChanging(string value);
    partial void On_emailChanged();
    partial void On_userChanging(string value);
    partial void On_userChanged();
    partial void On_passwordChanging(string value);
    partial void On_passwordChanged();
    partial void On_positionChanging(int value);
    partial void On_positionChanged();
    #endregion
	
	public administrator()
	{
		this._reviews = new EntitySet<review>(new Action<review>(this.attach_reviews), new Action<review>(this.detach_reviews));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_email]", Storage="__email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string _email
	{
		get
		{
			return this.@__email;
		}
		set
		{
			if ((this.@__email != value))
			{
				this.On_emailChanging(value);
				this.SendPropertyChanging();
				this.@__email = value;
				this.SendPropertyChanged("_email");
				this.On_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_user]", Storage="__user", DbType="VarChar(200)")]
	public string _user
	{
		get
		{
			return this.@__user;
		}
		set
		{
			if ((this.@__user != value))
			{
				this.On_userChanging(value);
				this.SendPropertyChanging();
				this.@__user = value;
				this.SendPropertyChanged("_user");
				this.On_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_password]", Storage="__password", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string _password
	{
		get
		{
			return this.@__password;
		}
		set
		{
			if ((this.@__password != value))
			{
				this.On_passwordChanging(value);
				this.SendPropertyChanging();
				this.@__password = value;
				this.SendPropertyChanged("_password");
				this.On_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_position]", Storage="__position", DbType="Int NOT NULL")]
	public int _position
	{
		get
		{
			return this.@__position;
		}
		set
		{
			if ((this.@__position != value))
			{
				this.On_positionChanging(value);
				this.SendPropertyChanging();
				this.@__position = value;
				this.SendPropertyChanged("_position");
				this.On_positionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="administrator_review", Storage="_reviews", ThisKey="_id", OtherKey="_id_admin")]
	public EntitySet<review> reviews
	{
		get
		{
			return this._reviews;
		}
		set
		{
			this._reviews.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_reviews(review entity)
	{
		this.SendPropertyChanging();
		entity.administrator = this;
	}
	
	private void detach_reviews(review entity)
	{
		this.SendPropertyChanging();
		entity.administrator = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.author")]
public partial class author : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string @__name_author;
	
	private string @__description_author;
	
	private string @__IMG;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_name_authorChanging(string value);
    partial void On_name_authorChanged();
    partial void On_description_authorChanging(string value);
    partial void On_description_authorChanged();
    partial void On_IMGChanging(string value);
    partial void On_IMGChanged();
    #endregion
	
	public author()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name_author]", Storage="__name_author", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string _name_author
	{
		get
		{
			return this.@__name_author;
		}
		set
		{
			if ((this.@__name_author != value))
			{
				this.On_name_authorChanging(value);
				this.SendPropertyChanging();
				this.@__name_author = value;
				this.SendPropertyChanged("_name_author");
				this.On_name_authorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_description_author]", Storage="__description_author", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string _description_author
	{
		get
		{
			return this.@__description_author;
		}
		set
		{
			if ((this.@__description_author != value))
			{
				this.On_description_authorChanging(value);
				this.SendPropertyChanging();
				this.@__description_author = value;
				this.SendPropertyChanged("_description_author");
				this.On_description_authorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_IMG]", Storage="__IMG", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string _IMG
	{
		get
		{
			return this.@__IMG;
		}
		set
		{
			if ((this.@__IMG != value))
			{
				this.On_IMGChanging(value);
				this.SendPropertyChanging();
				this.@__IMG = value;
				this.SendPropertyChanged("_IMG");
				this.On_IMGChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.book_news")]
public partial class book_new : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_new;
	
	private string _title;
	
	private string _img;
	
	private string _content_new;
	
	private string _author_new;
	
	private System.Nullable<System.DateTime> _date_new;
	
	private string _short_title;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_newChanging(int value);
    partial void Onid_newChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void Oncontent_newChanging(string value);
    partial void Oncontent_newChanged();
    partial void Onauthor_newChanging(string value);
    partial void Onauthor_newChanged();
    partial void Ondate_newChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_newChanged();
    partial void Onshort_titleChanging(string value);
    partial void Onshort_titleChanged();
    #endregion
	
	public book_new()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_new", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_new
	{
		get
		{
			return this._id_new;
		}
		set
		{
			if ((this._id_new != value))
			{
				this.Onid_newChanging(value);
				this.SendPropertyChanging();
				this._id_new = value;
				this.SendPropertyChanged("id_new");
				this.Onid_newChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(250)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(250)")]
	public string img
	{
		get
		{
			return this._img;
		}
		set
		{
			if ((this._img != value))
			{
				this.OnimgChanging(value);
				this.SendPropertyChanging();
				this._img = value;
				this.SendPropertyChanged("img");
				this.OnimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content_new", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string content_new
	{
		get
		{
			return this._content_new;
		}
		set
		{
			if ((this._content_new != value))
			{
				this.Oncontent_newChanging(value);
				this.SendPropertyChanging();
				this._content_new = value;
				this.SendPropertyChanged("content_new");
				this.Oncontent_newChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_author_new", DbType="NVarChar(250)")]
	public string author_new
	{
		get
		{
			return this._author_new;
		}
		set
		{
			if ((this._author_new != value))
			{
				this.Onauthor_newChanging(value);
				this.SendPropertyChanging();
				this._author_new = value;
				this.SendPropertyChanged("author_new");
				this.Onauthor_newChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_new", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_new
	{
		get
		{
			return this._date_new;
		}
		set
		{
			if ((this._date_new != value))
			{
				this.Ondate_newChanging(value);
				this.SendPropertyChanging();
				this._date_new = value;
				this.SendPropertyChanged("date_new");
				this.Ondate_newChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_title", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string short_title
	{
		get
		{
			return this._short_title;
		}
		set
		{
			if ((this._short_title != value))
			{
				this.Onshort_titleChanging(value);
				this.SendPropertyChanging();
				this._short_title = value;
				this.SendPropertyChanged("short_title");
				this.Onshort_titleChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cart")]
public partial class cart : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string _id_user;
	
	private string _id_product;
	
	private int _quantity;
	
	private EntityRef<product> _product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void Onid_userChanging(string value);
    partial void Onid_userChanged();
    partial void Onid_productChanging(string value);
    partial void Onid_productChanged();
    partial void OnquantityChanging(int value);
    partial void OnquantityChanged();
    #endregion
	
	public cart()
	{
		this._product = default(EntityRef<product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string id_user
	{
		get
		{
			return this._id_user;
		}
		set
		{
			if ((this._id_user != value))
			{
				this.Onid_userChanging(value);
				this.SendPropertyChanging();
				this._id_user = value;
				this.SendPropertyChanged("id_user");
				this.Onid_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_product", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string id_product
	{
		get
		{
			return this._id_product;
		}
		set
		{
			if ((this._id_product != value))
			{
				if (this._product.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_productChanging(value);
				this.SendPropertyChanging();
				this._id_product = value;
				this.SendPropertyChanged("id_product");
				this.Onid_productChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int NOT NULL")]
	public int quantity
	{
		get
		{
			return this._quantity;
		}
		set
		{
			if ((this._quantity != value))
			{
				this.OnquantityChanging(value);
				this.SendPropertyChanging();
				this._quantity = value;
				this.SendPropertyChanged("quantity");
				this.OnquantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_cart", Storage="_product", ThisKey="id_product", OtherKey="_id", IsForeignKey=true)]
	public product product
	{
		get
		{
			return this._product.Entity;
		}
		set
		{
			product previousValue = this._product.Entity;
			if (((previousValue != value) 
						|| (this._product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product.Entity = null;
					previousValue.carts.Remove(this);
				}
				this._product.Entity = value;
				if ((value != null))
				{
					value.carts.Add(this);
					this._id_product = value._id;
				}
				else
				{
					this._id_product = default(string);
				}
				this.SendPropertyChanged("product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string @__id;
	
	private string @__name;
	
	private string @__description;
	
	private EntitySet<category_product> _category_products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(string value);
    partial void On_idChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_descriptionChanging(string value);
    partial void On_descriptionChanged();
    #endregion
	
	public category()
	{
		this._category_products = new EntitySet<category_product>(new Action<category_product>(this.attach_category_products), new Action<category_product>(this.detach_category_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string _name
	{
		get
		{
			return this.@__name;
		}
		set
		{
			if ((this.@__name != value))
			{
				this.On_nameChanging(value);
				this.SendPropertyChanging();
				this.@__name = value;
				this.SendPropertyChanged("_name");
				this.On_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_description]", Storage="__description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string _description
	{
		get
		{
			return this.@__description;
		}
		set
		{
			if ((this.@__description != value))
			{
				this.On_descriptionChanging(value);
				this.SendPropertyChanging();
				this.@__description = value;
				this.SendPropertyChanged("_description");
				this.On_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_product", Storage="_category_products", ThisKey="_id", OtherKey="_id_category")]
	public EntitySet<category_product> category_products
	{
		get
		{
			return this._category_products;
		}
		set
		{
			this._category_products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_category_products(category_product entity)
	{
		this.SendPropertyChanging();
		entity.category = this;
	}
	
	private void detach_category_products(category_product entity)
	{
		this.SendPropertyChanging();
		entity.category = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category_product")]
public partial class category_product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string @__id_product;
	
	private string @__id_category;
	
	private EntityRef<category> _category;
	
	private EntityRef<product> _product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_id_productChanging(string value);
    partial void On_id_productChanged();
    partial void On_id_categoryChanging(string value);
    partial void On_id_categoryChanged();
    #endregion
	
	public category_product()
	{
		this._category = default(EntityRef<category>);
		this._product = default(EntityRef<product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_product]", Storage="__id_product", DbType="VarChar(30)")]
	public string _id_product
	{
		get
		{
			return this.@__id_product;
		}
		set
		{
			if ((this.@__id_product != value))
			{
				this.On_id_productChanging(value);
				this.SendPropertyChanging();
				this.@__id_product = value;
				this.SendPropertyChanged("_id_product");
				this.On_id_productChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_category]", Storage="__id_category", DbType="VarChar(30)")]
	public string _id_category
	{
		get
		{
			return this.@__id_category;
		}
		set
		{
			if ((this.@__id_category != value))
			{
				this.On_id_categoryChanging(value);
				this.SendPropertyChanging();
				this.@__id_category = value;
				this.SendPropertyChanged("_id_category");
				this.On_id_categoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_category_product", Storage="_category", ThisKey="_id_category", OtherKey="_id", IsForeignKey=true)]
	public category category
	{
		get
		{
			return this._category.Entity;
		}
		set
		{
			category previousValue = this._category.Entity;
			if (((previousValue != value) 
						|| (this._category.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._category.Entity = null;
					previousValue.category_products.Remove(this);
				}
				this._category.Entity = value;
				if ((value != null))
				{
					value.category_products.Add(this);
					this.@__id_category = value._id;
				}
				else
				{
					this.@__id_category = default(string);
				}
				this.SendPropertyChanged("category");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_product", Storage="_product", ThisKey="_id_product", OtherKey="_id", IsForeignKey=true)]
	public product product
	{
		get
		{
			return this._product.Entity;
		}
		set
		{
			product previousValue = this._product.Entity;
			if (((previousValue != value) 
						|| (this._product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product.Entity = null;
					previousValue.category_products.Remove(this);
				}
				this._product.Entity = value;
				if ((value != null))
				{
					value.category_products.Add(this);
					this.@__id_product = value._id;
				}
				else
				{
					this.@__id_product = default(string);
				}
				this.SendPropertyChanged("product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customer")]
public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string @__email;
	
	private string @__user;
	
	private string @__password;
	
	private string @__name;
	
	private string @__status;
	
	private EntitySet<customer_address> _customer_addresses;
	
	private EntitySet<review> _reviews;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_emailChanging(string value);
    partial void On_emailChanged();
    partial void On_userChanging(string value);
    partial void On_userChanged();
    partial void On_passwordChanging(string value);
    partial void On_passwordChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_statusChanging(string value);
    partial void On_statusChanged();
    #endregion
	
	public customer()
	{
		this._customer_addresses = new EntitySet<customer_address>(new Action<customer_address>(this.attach_customer_addresses), new Action<customer_address>(this.detach_customer_addresses));
		this._reviews = new EntitySet<review>(new Action<review>(this.attach_reviews), new Action<review>(this.detach_reviews));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_email]", Storage="__email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string _email
	{
		get
		{
			return this.@__email;
		}
		set
		{
			if ((this.@__email != value))
			{
				this.On_emailChanging(value);
				this.SendPropertyChanging();
				this.@__email = value;
				this.SendPropertyChanged("_email");
				this.On_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_user]", Storage="__user", DbType="VarChar(200)")]
	public string _user
	{
		get
		{
			return this.@__user;
		}
		set
		{
			if ((this.@__user != value))
			{
				this.On_userChanging(value);
				this.SendPropertyChanging();
				this.@__user = value;
				this.SendPropertyChanged("_user");
				this.On_userChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_password]", Storage="__password", DbType="VarChar(200)")]
	public string _password
	{
		get
		{
			return this.@__password;
		}
		set
		{
			if ((this.@__password != value))
			{
				this.On_passwordChanging(value);
				this.SendPropertyChanging();
				this.@__password = value;
				this.SendPropertyChanged("_password");
				this.On_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string _name
	{
		get
		{
			return this.@__name;
		}
		set
		{
			if ((this.@__name != value))
			{
				this.On_nameChanging(value);
				this.SendPropertyChanging();
				this.@__name = value;
				this.SendPropertyChanged("_name");
				this.On_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_status]", Storage="__status", DbType="NVarChar(50)")]
	public string _status
	{
		get
		{
			return this.@__status;
		}
		set
		{
			if ((this.@__status != value))
			{
				this.On_statusChanging(value);
				this.SendPropertyChanging();
				this.@__status = value;
				this.SendPropertyChanged("_status");
				this.On_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_customer_address", Storage="_customer_addresses", ThisKey="_id", OtherKey="_id_customer")]
	public EntitySet<customer_address> customer_addresses
	{
		get
		{
			return this._customer_addresses;
		}
		set
		{
			this._customer_addresses.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_review", Storage="_reviews", ThisKey="_id", OtherKey="_id_customer")]
	public EntitySet<review> reviews
	{
		get
		{
			return this._reviews;
		}
		set
		{
			this._reviews.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_customer_addresses(customer_address entity)
	{
		this.SendPropertyChanging();
		entity.customer = this;
	}
	
	private void detach_customer_addresses(customer_address entity)
	{
		this.SendPropertyChanging();
		entity.customer = null;
	}
	
	private void attach_reviews(review entity)
	{
		this.SendPropertyChanging();
		entity.customer = this;
	}
	
	private void detach_reviews(review entity)
	{
		this.SendPropertyChanging();
		entity.customer = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customer_address")]
public partial class customer_address : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string @__adddress_full;
	
	private string @__email;
	
	private string @__phone;
	
	private string @__company;
	
	private string @__zipe_code;
	
	private string @__nation;
	
	private string @__city;
	
	private string @__district;
	
	private System.Nullable<int> @__id_customer;
	
	private string @__name;
	
	private EntitySet<order_product> _order_products;
	
	private EntityRef<customer> _customer;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_adddress_fullChanging(string value);
    partial void On_adddress_fullChanged();
    partial void On_emailChanging(string value);
    partial void On_emailChanged();
    partial void On_phoneChanging(string value);
    partial void On_phoneChanged();
    partial void On_companyChanging(string value);
    partial void On_companyChanged();
    partial void On_zipe_codeChanging(string value);
    partial void On_zipe_codeChanged();
    partial void On_nationChanging(string value);
    partial void On_nationChanged();
    partial void On_cityChanging(string value);
    partial void On_cityChanged();
    partial void On_districtChanging(string value);
    partial void On_districtChanged();
    partial void On_id_customerChanging(System.Nullable<int> value);
    partial void On_id_customerChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    #endregion
	
	public customer_address()
	{
		this._order_products = new EntitySet<order_product>(new Action<order_product>(this.attach_order_products), new Action<order_product>(this.detach_order_products));
		this._customer = default(EntityRef<customer>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_adddress_full]", Storage="__adddress_full", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string _adddress_full
	{
		get
		{
			return this.@__adddress_full;
		}
		set
		{
			if ((this.@__adddress_full != value))
			{
				this.On_adddress_fullChanging(value);
				this.SendPropertyChanging();
				this.@__adddress_full = value;
				this.SendPropertyChanged("_adddress_full");
				this.On_adddress_fullChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_email]", Storage="__email", DbType="VarChar(200)")]
	public string _email
	{
		get
		{
			return this.@__email;
		}
		set
		{
			if ((this.@__email != value))
			{
				this.On_emailChanging(value);
				this.SendPropertyChanging();
				this.@__email = value;
				this.SendPropertyChanged("_email");
				this.On_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_phone]", Storage="__phone", DbType="NVarChar(255)")]
	public string _phone
	{
		get
		{
			return this.@__phone;
		}
		set
		{
			if ((this.@__phone != value))
			{
				this.On_phoneChanging(value);
				this.SendPropertyChanging();
				this.@__phone = value;
				this.SendPropertyChanged("_phone");
				this.On_phoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_company]", Storage="__company", DbType="NVarChar(255)")]
	public string _company
	{
		get
		{
			return this.@__company;
		}
		set
		{
			if ((this.@__company != value))
			{
				this.On_companyChanging(value);
				this.SendPropertyChanging();
				this.@__company = value;
				this.SendPropertyChanged("_company");
				this.On_companyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_zipe_code]", Storage="__zipe_code", DbType="NVarChar(100)")]
	public string _zipe_code
	{
		get
		{
			return this.@__zipe_code;
		}
		set
		{
			if ((this.@__zipe_code != value))
			{
				this.On_zipe_codeChanging(value);
				this.SendPropertyChanging();
				this.@__zipe_code = value;
				this.SendPropertyChanged("_zipe_code");
				this.On_zipe_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_nation]", Storage="__nation", DbType="NVarChar(100)")]
	public string _nation
	{
		get
		{
			return this.@__nation;
		}
		set
		{
			if ((this.@__nation != value))
			{
				this.On_nationChanging(value);
				this.SendPropertyChanging();
				this.@__nation = value;
				this.SendPropertyChanged("_nation");
				this.On_nationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_city]", Storage="__city", DbType="NVarChar(100)")]
	public string _city
	{
		get
		{
			return this.@__city;
		}
		set
		{
			if ((this.@__city != value))
			{
				this.On_cityChanging(value);
				this.SendPropertyChanging();
				this.@__city = value;
				this.SendPropertyChanged("_city");
				this.On_cityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_district]", Storage="__district", DbType="NVarChar(100)")]
	public string _district
	{
		get
		{
			return this.@__district;
		}
		set
		{
			if ((this.@__district != value))
			{
				this.On_districtChanging(value);
				this.SendPropertyChanging();
				this.@__district = value;
				this.SendPropertyChanged("_district");
				this.On_districtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_customer]", Storage="__id_customer", DbType="Int")]
	public System.Nullable<int> _id_customer
	{
		get
		{
			return this.@__id_customer;
		}
		set
		{
			if ((this.@__id_customer != value))
			{
				this.On_id_customerChanging(value);
				this.SendPropertyChanging();
				this.@__id_customer = value;
				this.SendPropertyChanged("_id_customer");
				this.On_id_customerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="NVarChar(200)")]
	public string _name
	{
		get
		{
			return this.@__name;
		}
		set
		{
			if ((this.@__name != value))
			{
				this.On_nameChanging(value);
				this.SendPropertyChanging();
				this.@__name = value;
				this.SendPropertyChanged("_name");
				this.On_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_address_order_product", Storage="_order_products", ThisKey="_id", OtherKey="_id_customer_address")]
	public EntitySet<order_product> order_products
	{
		get
		{
			return this._order_products;
		}
		set
		{
			this._order_products.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_customer_address", Storage="_customer", ThisKey="_id_customer", OtherKey="_id", IsForeignKey=true)]
	public customer customer
	{
		get
		{
			return this._customer.Entity;
		}
		set
		{
			customer previousValue = this._customer.Entity;
			if (((previousValue != value) 
						|| (this._customer.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._customer.Entity = null;
					previousValue.customer_addresses.Remove(this);
				}
				this._customer.Entity = value;
				if ((value != null))
				{
					value.customer_addresses.Add(this);
					this.@__id_customer = value._id;
				}
				else
				{
					this.@__id_customer = default(Nullable<int>);
				}
				this.SendPropertyChanged("customer");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_order_products(order_product entity)
	{
		this.SendPropertyChanging();
		entity.customer_address = this;
	}
	
	private void detach_order_products(order_product entity)
	{
		this.SendPropertyChanging();
		entity.customer_address = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_product")]
public partial class order_product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private System.Nullable<System.DateTime> @__date;
	
	private string @__status_paymen;
	
	private string @__status_delivery;
	
	private double @__total_bill;
	
	private System.Nullable<double> @__total_weight;
	
	private System.Nullable<double> @__fee_delivery;
	
	private int @__payment_id;
	
	private System.Nullable<int> @__customer_id;
	
	private System.Nullable<int> @__id_customer_address;
	
	private string @__status_bill;
	
	private EntitySet<ref_product_order> _ref_product_orders;
	
	private EntityRef<customer_address> _customer_address;
	
	private EntityRef<paymen> _paymen;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_dateChanging(System.Nullable<System.DateTime> value);
    partial void On_dateChanged();
    partial void On_status_paymenChanging(string value);
    partial void On_status_paymenChanged();
    partial void On_status_deliveryChanging(string value);
    partial void On_status_deliveryChanged();
    partial void On_total_billChanging(double value);
    partial void On_total_billChanged();
    partial void On_total_weightChanging(System.Nullable<double> value);
    partial void On_total_weightChanged();
    partial void On_fee_deliveryChanging(System.Nullable<double> value);
    partial void On_fee_deliveryChanged();
    partial void On_payment_idChanging(int value);
    partial void On_payment_idChanged();
    partial void On_customer_idChanging(System.Nullable<int> value);
    partial void On_customer_idChanged();
    partial void On_id_customer_addressChanging(System.Nullable<int> value);
    partial void On_id_customer_addressChanged();
    partial void On_status_billChanging(string value);
    partial void On_status_billChanged();
    #endregion
	
	public order_product()
	{
		this._ref_product_orders = new EntitySet<ref_product_order>(new Action<ref_product_order>(this.attach_ref_product_orders), new Action<ref_product_order>(this.detach_ref_product_orders));
		this._customer_address = default(EntityRef<customer_address>);
		this._paymen = default(EntityRef<paymen>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_date]", Storage="__date", DbType="DateTime")]
	public System.Nullable<System.DateTime> _date
	{
		get
		{
			return this.@__date;
		}
		set
		{
			if ((this.@__date != value))
			{
				this.On_dateChanging(value);
				this.SendPropertyChanging();
				this.@__date = value;
				this.SendPropertyChanged("_date");
				this.On_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_status_paymen]", Storage="__status_paymen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string _status_paymen
	{
		get
		{
			return this.@__status_paymen;
		}
		set
		{
			if ((this.@__status_paymen != value))
			{
				this.On_status_paymenChanging(value);
				this.SendPropertyChanging();
				this.@__status_paymen = value;
				this.SendPropertyChanged("_status_paymen");
				this.On_status_paymenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_status_delivery]", Storage="__status_delivery", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string _status_delivery
	{
		get
		{
			return this.@__status_delivery;
		}
		set
		{
			if ((this.@__status_delivery != value))
			{
				this.On_status_deliveryChanging(value);
				this.SendPropertyChanging();
				this.@__status_delivery = value;
				this.SendPropertyChanged("_status_delivery");
				this.On_status_deliveryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_total_bill]", Storage="__total_bill", DbType="Float NOT NULL")]
	public double _total_bill
	{
		get
		{
			return this.@__total_bill;
		}
		set
		{
			if ((this.@__total_bill != value))
			{
				this.On_total_billChanging(value);
				this.SendPropertyChanging();
				this.@__total_bill = value;
				this.SendPropertyChanged("_total_bill");
				this.On_total_billChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_total_weight]", Storage="__total_weight", DbType="Float")]
	public System.Nullable<double> _total_weight
	{
		get
		{
			return this.@__total_weight;
		}
		set
		{
			if ((this.@__total_weight != value))
			{
				this.On_total_weightChanging(value);
				this.SendPropertyChanging();
				this.@__total_weight = value;
				this.SendPropertyChanged("_total_weight");
				this.On_total_weightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_fee_delivery]", Storage="__fee_delivery", DbType="Float")]
	public System.Nullable<double> _fee_delivery
	{
		get
		{
			return this.@__fee_delivery;
		}
		set
		{
			if ((this.@__fee_delivery != value))
			{
				this.On_fee_deliveryChanging(value);
				this.SendPropertyChanging();
				this.@__fee_delivery = value;
				this.SendPropertyChanged("_fee_delivery");
				this.On_fee_deliveryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_payment_id]", Storage="__payment_id", DbType="Int NOT NULL")]
	public int _payment_id
	{
		get
		{
			return this.@__payment_id;
		}
		set
		{
			if ((this.@__payment_id != value))
			{
				this.On_payment_idChanging(value);
				this.SendPropertyChanging();
				this.@__payment_id = value;
				this.SendPropertyChanged("_payment_id");
				this.On_payment_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_customer_id]", Storage="__customer_id", DbType="Int")]
	public System.Nullable<int> _customer_id
	{
		get
		{
			return this.@__customer_id;
		}
		set
		{
			if ((this.@__customer_id != value))
			{
				this.On_customer_idChanging(value);
				this.SendPropertyChanging();
				this.@__customer_id = value;
				this.SendPropertyChanged("_customer_id");
				this.On_customer_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_customer_address]", Storage="__id_customer_address", DbType="Int")]
	public System.Nullable<int> _id_customer_address
	{
		get
		{
			return this.@__id_customer_address;
		}
		set
		{
			if ((this.@__id_customer_address != value))
			{
				this.On_id_customer_addressChanging(value);
				this.SendPropertyChanging();
				this.@__id_customer_address = value;
				this.SendPropertyChanged("_id_customer_address");
				this.On_id_customer_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_status_bill]", Storage="__status_bill", DbType="NVarChar(100)")]
	public string _status_bill
	{
		get
		{
			return this.@__status_bill;
		}
		set
		{
			if ((this.@__status_bill != value))
			{
				this.On_status_billChanging(value);
				this.SendPropertyChanging();
				this.@__status_bill = value;
				this.SendPropertyChanged("_status_bill");
				this.On_status_billChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_product_ref_product_order", Storage="_ref_product_orders", ThisKey="_id", OtherKey="_id_order")]
	public EntitySet<ref_product_order> ref_product_orders
	{
		get
		{
			return this._ref_product_orders;
		}
		set
		{
			this._ref_product_orders.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_address_order_product", Storage="_customer_address", ThisKey="_id_customer_address", OtherKey="_id", IsForeignKey=true)]
	public customer_address customer_address
	{
		get
		{
			return this._customer_address.Entity;
		}
		set
		{
			customer_address previousValue = this._customer_address.Entity;
			if (((previousValue != value) 
						|| (this._customer_address.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._customer_address.Entity = null;
					previousValue.order_products.Remove(this);
				}
				this._customer_address.Entity = value;
				if ((value != null))
				{
					value.order_products.Add(this);
					this.@__id_customer_address = value._id;
				}
				else
				{
					this.@__id_customer_address = default(Nullable<int>);
				}
				this.SendPropertyChanged("customer_address");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paymen_order_product", Storage="_paymen", ThisKey="_payment_id", OtherKey="_payment_id", IsForeignKey=true)]
	public paymen paymen
	{
		get
		{
			return this._paymen.Entity;
		}
		set
		{
			paymen previousValue = this._paymen.Entity;
			if (((previousValue != value) 
						|| (this._paymen.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._paymen.Entity = null;
					previousValue.order_products.Remove(this);
				}
				this._paymen.Entity = value;
				if ((value != null))
				{
					value.order_products.Add(this);
					this.@__payment_id = value._payment_id;
				}
				else
				{
					this.@__payment_id = default(int);
				}
				this.SendPropertyChanged("paymen");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ref_product_orders(ref_product_order entity)
	{
		this.SendPropertyChanging();
		entity.order_product = this;
	}
	
	private void detach_ref_product_orders(ref_product_order entity)
	{
		this.SendPropertyChanging();
		entity.order_product = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.paymen")]
public partial class paymen : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__payment_id;
	
	private string @__content;
	
	private EntitySet<order_product> _order_products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_payment_idChanging(int value);
    partial void On_payment_idChanged();
    partial void On_contentChanging(string value);
    partial void On_contentChanged();
    #endregion
	
	public paymen()
	{
		this._order_products = new EntitySet<order_product>(new Action<order_product>(this.attach_order_products), new Action<order_product>(this.detach_order_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_payment_id]", Storage="__payment_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _payment_id
	{
		get
		{
			return this.@__payment_id;
		}
		set
		{
			if ((this.@__payment_id != value))
			{
				this.On_payment_idChanging(value);
				this.SendPropertyChanging();
				this.@__payment_id = value;
				this.SendPropertyChanged("_payment_id");
				this.On_payment_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_content]", Storage="__content", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string _content
	{
		get
		{
			return this.@__content;
		}
		set
		{
			if ((this.@__content != value))
			{
				this.On_contentChanging(value);
				this.SendPropertyChanging();
				this.@__content = value;
				this.SendPropertyChanged("_content");
				this.On_contentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="paymen_order_product", Storage="_order_products", ThisKey="_payment_id", OtherKey="_payment_id")]
	public EntitySet<order_product> order_products
	{
		get
		{
			return this._order_products;
		}
		set
		{
			this._order_products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_order_products(order_product entity)
	{
		this.SendPropertyChanging();
		entity.paymen = this;
	}
	
	private void detach_order_products(order_product entity)
	{
		this.SendPropertyChanging();
		entity.paymen = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producer")]
public partial class producer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string @__name;
	
	private string @__description;
	
	private EntitySet<product> _products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_descriptionChanging(string value);
    partial void On_descriptionChanged();
    #endregion
	
	public producer()
	{
		this._products = new EntitySet<product>(new Action<product>(this.attach_products), new Action<product>(this.detach_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string _name
	{
		get
		{
			return this.@__name;
		}
		set
		{
			if ((this.@__name != value))
			{
				this.On_nameChanging(value);
				this.SendPropertyChanging();
				this.@__name = value;
				this.SendPropertyChanged("_name");
				this.On_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_description]", Storage="__description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string _description
	{
		get
		{
			return this.@__description;
		}
		set
		{
			if ((this.@__description != value))
			{
				this.On_descriptionChanging(value);
				this.SendPropertyChanging();
				this.@__description = value;
				this.SendPropertyChanged("_description");
				this.On_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producer_product", Storage="_products", ThisKey="_id", OtherKey="_id_producer")]
	public EntitySet<product> products
	{
		get
		{
			return this._products;
		}
		set
		{
			this._products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_products(product entity)
	{
		this.SendPropertyChanging();
		entity.producer = this;
	}
	
	private void detach_products(product entity)
	{
		this.SendPropertyChanging();
		entity.producer = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string @__id;
	
	private string @__name;
	
	private string @__IMG;
	
	private System.Nullable<decimal> @__price_pages;
	
	private double @__price;
	
	private int @__pages;
	
	private int @__repository;
	
	private double @__weight;
	
	private string @__content;
	
	private string @__status;
	
	private System.DateTime @__date;
	
	private int @__year_of_creation;
	
	private int @__id_producer;
	
	private int @__type;
	
	private int @__author_id;
	
	private EntitySet<cart> _carts;
	
	private EntitySet<category_product> _category_products;
	
	private EntitySet<ref_product_order> _ref_product_orders;
	
	private EntitySet<review> _reviews;
	
	private EntityRef<producer> _producer;
	
	private EntityRef<product_type> _product_type;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(string value);
    partial void On_idChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_IMGChanging(string value);
    partial void On_IMGChanged();
    partial void On_price_pagesChanging(System.Nullable<decimal> value);
    partial void On_price_pagesChanged();
    partial void On_priceChanging(double value);
    partial void On_priceChanged();
    partial void On_pagesChanging(int value);
    partial void On_pagesChanged();
    partial void On_repositoryChanging(int value);
    partial void On_repositoryChanged();
    partial void On_weightChanging(double value);
    partial void On_weightChanged();
    partial void On_contentChanging(string value);
    partial void On_contentChanged();
    partial void On_statusChanging(string value);
    partial void On_statusChanged();
    partial void On_dateChanging(System.DateTime value);
    partial void On_dateChanged();
    partial void On_year_of_creationChanging(int value);
    partial void On_year_of_creationChanged();
    partial void On_id_producerChanging(int value);
    partial void On_id_producerChanged();
    partial void On_typeChanging(int value);
    partial void On_typeChanged();
    partial void On_author_idChanging(int value);
    partial void On_author_idChanged();
    #endregion
	
	public product()
	{
		this._carts = new EntitySet<cart>(new Action<cart>(this.attach_carts), new Action<cart>(this.detach_carts));
		this._category_products = new EntitySet<category_product>(new Action<category_product>(this.attach_category_products), new Action<category_product>(this.detach_category_products));
		this._ref_product_orders = new EntitySet<ref_product_order>(new Action<ref_product_order>(this.attach_ref_product_orders), new Action<ref_product_order>(this.detach_ref_product_orders));
		this._reviews = new EntitySet<review>(new Action<review>(this.attach_reviews), new Action<review>(this.detach_reviews));
		this._producer = default(EntityRef<producer>);
		this._product_type = default(EntityRef<product_type>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string _name
	{
		get
		{
			return this.@__name;
		}
		set
		{
			if ((this.@__name != value))
			{
				this.On_nameChanging(value);
				this.SendPropertyChanging();
				this.@__name = value;
				this.SendPropertyChanged("_name");
				this.On_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_IMG]", Storage="__IMG", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string _IMG
	{
		get
		{
			return this.@__IMG;
		}
		set
		{
			if ((this.@__IMG != value))
			{
				this.On_IMGChanging(value);
				this.SendPropertyChanging();
				this.@__IMG = value;
				this.SendPropertyChanged("_IMG");
				this.On_IMGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_price_pages]", Storage="__price_pages", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> _price_pages
	{
		get
		{
			return this.@__price_pages;
		}
		set
		{
			if ((this.@__price_pages != value))
			{
				this.On_price_pagesChanging(value);
				this.SendPropertyChanging();
				this.@__price_pages = value;
				this.SendPropertyChanged("_price_pages");
				this.On_price_pagesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_price]", Storage="__price", DbType="Float NOT NULL")]
	public double _price
	{
		get
		{
			return this.@__price;
		}
		set
		{
			if ((this.@__price != value))
			{
				this.On_priceChanging(value);
				this.SendPropertyChanging();
				this.@__price = value;
				this.SendPropertyChanged("_price");
				this.On_priceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_pages]", Storage="__pages", DbType="Int NOT NULL")]
	public int _pages
	{
		get
		{
			return this.@__pages;
		}
		set
		{
			if ((this.@__pages != value))
			{
				this.On_pagesChanging(value);
				this.SendPropertyChanging();
				this.@__pages = value;
				this.SendPropertyChanged("_pages");
				this.On_pagesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_repository]", Storage="__repository", DbType="Int NOT NULL")]
	public int _repository
	{
		get
		{
			return this.@__repository;
		}
		set
		{
			if ((this.@__repository != value))
			{
				this.On_repositoryChanging(value);
				this.SendPropertyChanging();
				this.@__repository = value;
				this.SendPropertyChanged("_repository");
				this.On_repositoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_weight]", Storage="__weight", DbType="Float NOT NULL")]
	public double _weight
	{
		get
		{
			return this.@__weight;
		}
		set
		{
			if ((this.@__weight != value))
			{
				this.On_weightChanging(value);
				this.SendPropertyChanging();
				this.@__weight = value;
				this.SendPropertyChanged("_weight");
				this.On_weightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_content]", Storage="__content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string _content
	{
		get
		{
			return this.@__content;
		}
		set
		{
			if ((this.@__content != value))
			{
				this.On_contentChanging(value);
				this.SendPropertyChanging();
				this.@__content = value;
				this.SendPropertyChanged("_content");
				this.On_contentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_status]", Storage="__status", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string _status
	{
		get
		{
			return this.@__status;
		}
		set
		{
			if ((this.@__status != value))
			{
				this.On_statusChanging(value);
				this.SendPropertyChanging();
				this.@__status = value;
				this.SendPropertyChanged("_status");
				this.On_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_date]", Storage="__date", DbType="Date NOT NULL")]
	public System.DateTime _date
	{
		get
		{
			return this.@__date;
		}
		set
		{
			if ((this.@__date != value))
			{
				this.On_dateChanging(value);
				this.SendPropertyChanging();
				this.@__date = value;
				this.SendPropertyChanged("_date");
				this.On_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_year_of_creation]", Storage="__year_of_creation", DbType="Int NOT NULL")]
	public int _year_of_creation
	{
		get
		{
			return this.@__year_of_creation;
		}
		set
		{
			if ((this.@__year_of_creation != value))
			{
				this.On_year_of_creationChanging(value);
				this.SendPropertyChanging();
				this.@__year_of_creation = value;
				this.SendPropertyChanged("_year_of_creation");
				this.On_year_of_creationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_producer]", Storage="__id_producer", DbType="Int NOT NULL")]
	public int _id_producer
	{
		get
		{
			return this.@__id_producer;
		}
		set
		{
			if ((this.@__id_producer != value))
			{
				this.On_id_producerChanging(value);
				this.SendPropertyChanging();
				this.@__id_producer = value;
				this.SendPropertyChanged("_id_producer");
				this.On_id_producerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_type]", Storage="__type", DbType="Int NOT NULL")]
	public int _type
	{
		get
		{
			return this.@__type;
		}
		set
		{
			if ((this.@__type != value))
			{
				this.On_typeChanging(value);
				this.SendPropertyChanging();
				this.@__type = value;
				this.SendPropertyChanged("_type");
				this.On_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_author_id]", Storage="__author_id", DbType="Int NOT NULL")]
	public int _author_id
	{
		get
		{
			return this.@__author_id;
		}
		set
		{
			if ((this.@__author_id != value))
			{
				this.On_author_idChanging(value);
				this.SendPropertyChanging();
				this.@__author_id = value;
				this.SendPropertyChanged("_author_id");
				this.On_author_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_cart", Storage="_carts", ThisKey="_id", OtherKey="id_product")]
	public EntitySet<cart> carts
	{
		get
		{
			return this._carts;
		}
		set
		{
			this._carts.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_product", Storage="_category_products", ThisKey="_id", OtherKey="_id_product")]
	public EntitySet<category_product> category_products
	{
		get
		{
			return this._category_products;
		}
		set
		{
			this._category_products.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_ref_product_order", Storage="_ref_product_orders", ThisKey="_id", OtherKey="_id_product")]
	public EntitySet<ref_product_order> ref_product_orders
	{
		get
		{
			return this._ref_product_orders;
		}
		set
		{
			this._ref_product_orders.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_review", Storage="_reviews", ThisKey="_id", OtherKey="_id_Product")]
	public EntitySet<review> reviews
	{
		get
		{
			return this._reviews;
		}
		set
		{
			this._reviews.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producer_product", Storage="_producer", ThisKey="_id_producer", OtherKey="_id", IsForeignKey=true)]
	public producer producer
	{
		get
		{
			return this._producer.Entity;
		}
		set
		{
			producer previousValue = this._producer.Entity;
			if (((previousValue != value) 
						|| (this._producer.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._producer.Entity = null;
					previousValue.products.Remove(this);
				}
				this._producer.Entity = value;
				if ((value != null))
				{
					value.products.Add(this);
					this.@__id_producer = value._id;
				}
				else
				{
					this.@__id_producer = default(int);
				}
				this.SendPropertyChanged("producer");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_type_product", Storage="_product_type", ThisKey="_type", OtherKey="_id", IsForeignKey=true)]
	public product_type product_type
	{
		get
		{
			return this._product_type.Entity;
		}
		set
		{
			product_type previousValue = this._product_type.Entity;
			if (((previousValue != value) 
						|| (this._product_type.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product_type.Entity = null;
					previousValue.products.Remove(this);
				}
				this._product_type.Entity = value;
				if ((value != null))
				{
					value.products.Add(this);
					this.@__type = value._id;
				}
				else
				{
					this.@__type = default(int);
				}
				this.SendPropertyChanged("product_type");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_carts(cart entity)
	{
		this.SendPropertyChanging();
		entity.product = this;
	}
	
	private void detach_carts(cart entity)
	{
		this.SendPropertyChanging();
		entity.product = null;
	}
	
	private void attach_category_products(category_product entity)
	{
		this.SendPropertyChanging();
		entity.product = this;
	}
	
	private void detach_category_products(category_product entity)
	{
		this.SendPropertyChanging();
		entity.product = null;
	}
	
	private void attach_ref_product_orders(ref_product_order entity)
	{
		this.SendPropertyChanging();
		entity.product = this;
	}
	
	private void detach_ref_product_orders(ref_product_order entity)
	{
		this.SendPropertyChanging();
		entity.product = null;
	}
	
	private void attach_reviews(review entity)
	{
		this.SendPropertyChanging();
		entity.product = this;
	}
	
	private void detach_reviews(review entity)
	{
		this.SendPropertyChanging();
		entity.product = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_type")]
public partial class product_type : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private string @__name;
	
	private string @__description;
	
	private EntitySet<product> _products;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_descriptionChanging(string value);
    partial void On_descriptionChanged();
    #endregion
	
	public product_type()
	{
		this._products = new EntitySet<product>(new Action<product>(this.attach_products), new Action<product>(this.detach_products));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string _name
	{
		get
		{
			return this.@__name;
		}
		set
		{
			if ((this.@__name != value))
			{
				this.On_nameChanging(value);
				this.SendPropertyChanging();
				this.@__name = value;
				this.SendPropertyChanged("_name");
				this.On_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_description]", Storage="__description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string _description
	{
		get
		{
			return this.@__description;
		}
		set
		{
			if ((this.@__description != value))
			{
				this.On_descriptionChanging(value);
				this.SendPropertyChanging();
				this.@__description = value;
				this.SendPropertyChanged("_description");
				this.On_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_type_product", Storage="_products", ThisKey="_id", OtherKey="_type")]
	public EntitySet<product> products
	{
		get
		{
			return this._products;
		}
		set
		{
			this._products.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_products(product entity)
	{
		this.SendPropertyChanging();
		entity.product_type = this;
	}
	
	private void detach_products(product entity)
	{
		this.SendPropertyChanging();
		entity.product_type = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ref_product_order")]
public partial class ref_product_order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private System.Nullable<int> @__quantity;
	
	private System.Nullable<int> @__id_order;
	
	private string @__id_product;
	
	private System.Nullable<double> @__price;
	
	private EntityRef<order_product> _order_product;
	
	private EntityRef<product> _product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_quantityChanging(System.Nullable<int> value);
    partial void On_quantityChanged();
    partial void On_id_orderChanging(System.Nullable<int> value);
    partial void On_id_orderChanged();
    partial void On_id_productChanging(string value);
    partial void On_id_productChanged();
    partial void On_priceChanging(System.Nullable<double> value);
    partial void On_priceChanged();
    #endregion
	
	public ref_product_order()
	{
		this._order_product = default(EntityRef<order_product>);
		this._product = default(EntityRef<product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_quantity]", Storage="__quantity", DbType="Int")]
	public System.Nullable<int> _quantity
	{
		get
		{
			return this.@__quantity;
		}
		set
		{
			if ((this.@__quantity != value))
			{
				this.On_quantityChanging(value);
				this.SendPropertyChanging();
				this.@__quantity = value;
				this.SendPropertyChanged("_quantity");
				this.On_quantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_order]", Storage="__id_order", DbType="Int")]
	public System.Nullable<int> _id_order
	{
		get
		{
			return this.@__id_order;
		}
		set
		{
			if ((this.@__id_order != value))
			{
				this.On_id_orderChanging(value);
				this.SendPropertyChanging();
				this.@__id_order = value;
				this.SendPropertyChanged("_id_order");
				this.On_id_orderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_product]", Storage="__id_product", DbType="VarChar(30)")]
	public string _id_product
	{
		get
		{
			return this.@__id_product;
		}
		set
		{
			if ((this.@__id_product != value))
			{
				this.On_id_productChanging(value);
				this.SendPropertyChanging();
				this.@__id_product = value;
				this.SendPropertyChanged("_id_product");
				this.On_id_productChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_price]", Storage="__price", DbType="Float")]
	public System.Nullable<double> _price
	{
		get
		{
			return this.@__price;
		}
		set
		{
			if ((this.@__price != value))
			{
				this.On_priceChanging(value);
				this.SendPropertyChanging();
				this.@__price = value;
				this.SendPropertyChanged("_price");
				this.On_priceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_product_ref_product_order", Storage="_order_product", ThisKey="_id_order", OtherKey="_id", IsForeignKey=true)]
	public order_product order_product
	{
		get
		{
			return this._order_product.Entity;
		}
		set
		{
			order_product previousValue = this._order_product.Entity;
			if (((previousValue != value) 
						|| (this._order_product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._order_product.Entity = null;
					previousValue.ref_product_orders.Remove(this);
				}
				this._order_product.Entity = value;
				if ((value != null))
				{
					value.ref_product_orders.Add(this);
					this.@__id_order = value._id;
				}
				else
				{
					this.@__id_order = default(Nullable<int>);
				}
				this.SendPropertyChanged("order_product");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_ref_product_order", Storage="_product", ThisKey="_id_product", OtherKey="_id", IsForeignKey=true)]
	public product product
	{
		get
		{
			return this._product.Entity;
		}
		set
		{
			product previousValue = this._product.Entity;
			if (((previousValue != value) 
						|| (this._product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product.Entity = null;
					previousValue.ref_product_orders.Remove(this);
				}
				this._product.Entity = value;
				if ((value != null))
				{
					value.ref_product_orders.Add(this);
					this.@__id_product = value._id;
				}
				else
				{
					this.@__id_product = default(string);
				}
				this.SendPropertyChanged("product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.review")]
public partial class review : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int @__id;
	
	private System.Nullable<System.DateTime> @__date;
	
	private string @__comment;
	
	private System.Nullable<int> @__rating;
	
	private string @__title;
	
	private string @__id_Product;
	
	private System.Nullable<int> @__id_customer;
	
	private System.Nullable<int> @__id_admin;
	
	private EntityRef<administrator> _administrator;
	
	private EntityRef<customer> _customer;
	
	private EntityRef<product> _product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_idChanging(int value);
    partial void On_idChanged();
    partial void On_dateChanging(System.Nullable<System.DateTime> value);
    partial void On_dateChanged();
    partial void On_commentChanging(string value);
    partial void On_commentChanged();
    partial void On_ratingChanging(System.Nullable<int> value);
    partial void On_ratingChanged();
    partial void On_titleChanging(string value);
    partial void On_titleChanged();
    partial void On_id_ProductChanging(string value);
    partial void On_id_ProductChanged();
    partial void On_id_customerChanging(System.Nullable<int> value);
    partial void On_id_customerChanged();
    partial void On_id_adminChanging(System.Nullable<int> value);
    partial void On_id_adminChanged();
    #endregion
	
	public review()
	{
		this._administrator = default(EntityRef<administrator>);
		this._customer = default(EntityRef<customer>);
		this._product = default(EntityRef<product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id]", Storage="__id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int _id
	{
		get
		{
			return this.@__id;
		}
		set
		{
			if ((this.@__id != value))
			{
				this.On_idChanging(value);
				this.SendPropertyChanging();
				this.@__id = value;
				this.SendPropertyChanged("_id");
				this.On_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_date]", Storage="__date", DbType="Date")]
	public System.Nullable<System.DateTime> _date
	{
		get
		{
			return this.@__date;
		}
		set
		{
			if ((this.@__date != value))
			{
				this.On_dateChanging(value);
				this.SendPropertyChanging();
				this.@__date = value;
				this.SendPropertyChanged("_date");
				this.On_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_comment]", Storage="__comment", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string _comment
	{
		get
		{
			return this.@__comment;
		}
		set
		{
			if ((this.@__comment != value))
			{
				this.On_commentChanging(value);
				this.SendPropertyChanging();
				this.@__comment = value;
				this.SendPropertyChanged("_comment");
				this.On_commentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_rating]", Storage="__rating", DbType="Int")]
	public System.Nullable<int> _rating
	{
		get
		{
			return this.@__rating;
		}
		set
		{
			if ((this.@__rating != value))
			{
				this.On_ratingChanging(value);
				this.SendPropertyChanging();
				this.@__rating = value;
				this.SendPropertyChanged("_rating");
				this.On_ratingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_title]", Storage="__title", DbType="NVarChar(200)")]
	public string _title
	{
		get
		{
			return this.@__title;
		}
		set
		{
			if ((this.@__title != value))
			{
				this.On_titleChanging(value);
				this.SendPropertyChanging();
				this.@__title = value;
				this.SendPropertyChanged("_title");
				this.On_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_Product]", Storage="__id_Product", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string _id_Product
	{
		get
		{
			return this.@__id_Product;
		}
		set
		{
			if ((this.@__id_Product != value))
			{
				this.On_id_ProductChanging(value);
				this.SendPropertyChanging();
				this.@__id_Product = value;
				this.SendPropertyChanged("_id_Product");
				this.On_id_ProductChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_customer]", Storage="__id_customer", DbType="Int")]
	public System.Nullable<int> _id_customer
	{
		get
		{
			return this.@__id_customer;
		}
		set
		{
			if ((this.@__id_customer != value))
			{
				this.On_id_customerChanging(value);
				this.SendPropertyChanging();
				this.@__id_customer = value;
				this.SendPropertyChanged("_id_customer");
				this.On_id_customerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_id_admin]", Storage="__id_admin", DbType="Int")]
	public System.Nullable<int> _id_admin
	{
		get
		{
			return this.@__id_admin;
		}
		set
		{
			if ((this.@__id_admin != value))
			{
				this.On_id_adminChanging(value);
				this.SendPropertyChanging();
				this.@__id_admin = value;
				this.SendPropertyChanged("_id_admin");
				this.On_id_adminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="administrator_review", Storage="_administrator", ThisKey="_id_admin", OtherKey="_id", IsForeignKey=true)]
	public administrator administrator
	{
		get
		{
			return this._administrator.Entity;
		}
		set
		{
			administrator previousValue = this._administrator.Entity;
			if (((previousValue != value) 
						|| (this._administrator.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._administrator.Entity = null;
					previousValue.reviews.Remove(this);
				}
				this._administrator.Entity = value;
				if ((value != null))
				{
					value.reviews.Add(this);
					this.@__id_admin = value._id;
				}
				else
				{
					this.@__id_admin = default(Nullable<int>);
				}
				this.SendPropertyChanged("administrator");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_review", Storage="_customer", ThisKey="_id_customer", OtherKey="_id", IsForeignKey=true)]
	public customer customer
	{
		get
		{
			return this._customer.Entity;
		}
		set
		{
			customer previousValue = this._customer.Entity;
			if (((previousValue != value) 
						|| (this._customer.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._customer.Entity = null;
					previousValue.reviews.Remove(this);
				}
				this._customer.Entity = value;
				if ((value != null))
				{
					value.reviews.Add(this);
					this.@__id_customer = value._id;
				}
				else
				{
					this.@__id_customer = default(Nullable<int>);
				}
				this.SendPropertyChanged("customer");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_review", Storage="_product", ThisKey="_id_Product", OtherKey="_id", IsForeignKey=true)]
	public product product
	{
		get
		{
			return this._product.Entity;
		}
		set
		{
			product previousValue = this._product.Entity;
			if (((previousValue != value) 
						|| (this._product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product.Entity = null;
					previousValue.reviews.Remove(this);
				}
				this._product.Entity = value;
				if ((value != null))
				{
					value.reviews.Add(this);
					this.@__id_Product = value._id;
				}
				else
				{
					this.@__id_Product = default(string);
				}
				this.SendPropertyChanged("product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
