<?xml version="1.0" encoding="utf-8"?><Database Name="BookASMWAD" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=BookASMWAD;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BookASMWADConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.administrator" Member="administrators">
    <Type Name="administrator">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_email]" Member="_email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[_user]" Member="_user" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="[_password]" Member="_password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[_position]" Member="_position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="administrator_review" Member="reviews" ThisKey="_id" OtherKey="_id_admin" Type="review" />
    </Type>
  </Table>
  <Table Name="dbo.author" Member="authors">
    <Type Name="author">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_name_author]" Member="_name_author" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[_description_author]" Member="_description_author" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[_IMG]" Member="_IMG" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.book_news" Member="book_news">
    <Type Name="book_new">
      <Column Name="id_new" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="content_new" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="author_new" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="date_new" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="short_title" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.cart" Member="carts">
    <Type Name="cart">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="id_product" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="product_cart" Member="product" ThisKey="id_product" OtherKey="_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="[_id]" Member="_id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[_name]" Member="_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[_description]" Member="_description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="category_category_product" Member="category_products" ThisKey="_id" OtherKey="_id_category" Type="category_product" />
    </Type>
  </Table>
  <Table Name="dbo.category_product" Member="category_products">
    <Type Name="category_product">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_id_product]" Member="_id_product" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[_id_category]" Member="_id_category" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="category_category_product" Member="category" ThisKey="_id_category" OtherKey="_id" Type="category" IsForeignKey="true" />
      <Association Name="product_category_product" Member="product" ThisKey="_id_product" OtherKey="_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_email]" Member="_email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[_user]" Member="_user" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="[_password]" Member="_password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="[_name]" Member="_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[_status]" Member="_status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="customer_customer_address" Member="customer_addresses" ThisKey="_id" OtherKey="_id_customer" Type="customer_address" />
      <Association Name="customer_review" Member="reviews" ThisKey="_id" OtherKey="_id_customer" Type="review" />
    </Type>
  </Table>
  <Table Name="dbo.customer_address" Member="customer_addresses">
    <Type Name="customer_address">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_adddress_full]" Member="_adddress_full" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="[_email]" Member="_email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="[_phone]" Member="_phone" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[_company]" Member="_company" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[_zipe_code]" Member="_zipe_code" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[_nation]" Member="_nation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[_city]" Member="_city" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[_district]" Member="_district" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[_id_customer]" Member="_id_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_name]" Member="_name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="customer_address_order_product" Member="order_products" ThisKey="_id" OtherKey="_id_customer_address" Type="order_product" />
      <Association Name="customer_customer_address" Member="customer" ThisKey="_id_customer" OtherKey="_id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.order_product" Member="order_products">
    <Type Name="order_product">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_date]" Member="_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[_status_paymen]" Member="_status_paymen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="[_status_delivery]" Member="_status_delivery" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="[_total_bill]" Member="_total_bill" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[_total_weight]" Member="_total_weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[_fee_delivery]" Member="_fee_delivery" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[_payment_id]" Member="_payment_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_customer_id]" Member="_customer_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_id_customer_address]" Member="_id_customer_address" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_status_bill]" Member="_status_bill" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="order_product_ref_product_order" Member="ref_product_orders" ThisKey="_id" OtherKey="_id_order" Type="ref_product_order" />
      <Association Name="customer_address_order_product" Member="customer_address" ThisKey="_id_customer_address" OtherKey="_id" Type="customer_address" IsForeignKey="true" />
      <Association Name="paymen_order_product" Member="paymen" ThisKey="_payment_id" OtherKey="_payment_id" Type="paymen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.paymen" Member="paymens">
    <Type Name="paymen">
      <Column Name="[_payment_id]" Member="_payment_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_content]" Member="_content" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="paymen_order_product" Member="order_products" ThisKey="_payment_id" OtherKey="_payment_id" Type="order_product" />
    </Type>
  </Table>
  <Table Name="dbo.producer" Member="producers">
    <Type Name="producer">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_name]" Member="_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[_description]" Member="_description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="producer_product" Member="products" ThisKey="_id" OtherKey="_id_producer" Type="product" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="[_id]" Member="_id" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[_name]" Member="_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[_IMG]" Member="_IMG" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="[_price_pages]" Member="_price_pages" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[_price]" Member="_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[_pages]" Member="_pages" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_repository]" Member="_repository" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_weight]" Member="_weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[_content]" Member="_content" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[_status]" Member="_status" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[_date]" Member="_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[_year_of_creation]" Member="_year_of_creation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_id_producer]" Member="_id_producer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_type]" Member="_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_author_id]" Member="_author_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="product_cart" Member="carts" ThisKey="_id" OtherKey="id_product" Type="cart" />
      <Association Name="product_category_product" Member="category_products" ThisKey="_id" OtherKey="_id_product" Type="category_product" />
      <Association Name="product_ref_product_order" Member="ref_product_orders" ThisKey="_id" OtherKey="_id_product" Type="ref_product_order" />
      <Association Name="product_review" Member="reviews" ThisKey="_id" OtherKey="_id_Product" Type="review" />
      <Association Name="producer_product" Member="producer" ThisKey="_id_producer" OtherKey="_id" Type="producer" IsForeignKey="true" />
      <Association Name="product_type_product" Member="product_type" ThisKey="_type" OtherKey="_id" Type="product_type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.product_type" Member="product_types">
    <Type Name="product_type">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_name]" Member="_name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[_description]" Member="_description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="product_type_product" Member="products" ThisKey="_id" OtherKey="_type" Type="product" />
    </Type>
  </Table>
  <Table Name="dbo.ref_product_order" Member="ref_product_orders">
    <Type Name="ref_product_order">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_quantity]" Member="_quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_id_order]" Member="_id_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_id_product]" Member="_id_product" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="[_price]" Member="_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="order_product_ref_product_order" Member="order_product" ThisKey="_id_order" OtherKey="_id" Type="order_product" IsForeignKey="true" />
      <Association Name="product_ref_product_order" Member="product" ThisKey="_id_product" OtherKey="_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.review" Member="reviews">
    <Type Name="review">
      <Column Name="[_id]" Member="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[_date]" Member="_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[_comment]" Member="_comment" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[_rating]" Member="_rating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_title]" Member="_title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="[_id_Product]" Member="_id_Product" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[_id_customer]" Member="_id_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[_id_admin]" Member="_id_admin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="administrator_review" Member="administrator" ThisKey="_id_admin" OtherKey="_id" Type="administrator" IsForeignKey="true" />
      <Association Name="customer_review" Member="customer" ThisKey="_id_customer" OtherKey="_id" Type="customer" IsForeignKey="true" />
      <Association Name="product_review" Member="product" ThisKey="_id_Product" OtherKey="_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>